### ISSUE TITLE
Unable to import existing virsh vm

### ISSUE THREAD

**Issue by rorysavage77** [dmacvicar/terraform-provider-libvirt#1090]
FYI -

I am attempting to import an existing LibVert VM into this example terraform code base, and I am running into this bug.  Got any ideas?

OS: `Ubuntu 22.04.4 LTS`
Libert: 
    * virsh: `8.0.0
    * qemu: `6.2.0`
    * libvert: `8.0.0`

Code: (main.tf)
```hcl
resource "libvirt_domain" "vlab-01" {
  name   = "vlab-01"
  memory = 4096
  vcpu   = 4

  disk {
    volume_id = libvirt_volume.vlab-01_disk.id
  }

  network_interface {
    network_name = "default"
  }

  console {
    type        = "pty"
    target_port = "0"
    target_type = "serial"
  }

  graphics {
    type        = "spice"
    listen_type = "none"
  }

  boot {
    dev = ["hd"]
  }
}

resource "libvirt_volume" "vlab-01_disk" {
  name   = "vlab-01-disk"
  pool   = "default"
  format = "qcow2"
  size   = 53687 # size in MB
}
```
Code: (versions.tf)
```hcl
terraform {
  required_providers {
    libvirt = {
      source  = "dmacvicar/libvirt"
      version = "~> 0.7.6"
    }
  }
}
```
Code: (providers.tf)
```hcl
provider "libvirt" {
  uri = "qemu+ssh://REDACTED@REDACTED-IP/system"
}
```

Command line:
```bash
terraform import libvirt_domain.vlab-01 vlab-01
```

Error:
```shell
libvirt_domain.vlab-01: Importing from ID "vlab-01"...
libvirt_domain.vlab-01: Import prepared!
  Prepared libvirt_domain for import
libvirt_domain.vlab-01: Refreshing state... [id=vlab-01]
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵


Stack trace from the terraform-provider-libvirt_v0.7.6 plugin:

panic: uuid: Parse(vlab-01): invalid UUID length: 7

goroutine 91 [running]:
github.com/google/uuid.MustParse({0x1400000ffe0, 0x7})
        github.com/google/uuid@v1.3.0/uuid.go:163 +0x98
github.com/dmacvicar/terraform-provider-libvirt/libvirt.parseUUID(...)
        github.com/dmacvicar/terraform-provider-libvirt/libvirt/utils_libvirt.go:11
github.com/dmacvicar/terraform-provider-libvirt/libvirt.resourceLibvirtDomainRead({0x103911ae8?, 0x14000288300?}, 0x14000649700, {0x10375afc0?, 0x14000122528})
        github.com/dmacvicar/terraform-provider-libvirt/libvirt/resource_libvirt_domain.go:783 +0x150
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x1400018f0a0, {0x103911ae8, 0x14000288300}, 0xd?, {0x10375afc0, 0x14000122528})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:724 +0xe8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x1400018f0a0, {0x103911ae8, 0x14000288300}, 0x1400065f040, {0x10375afc0, 0x14000122528})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:1015 +0x418
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x140003dbe18, {0x103911ae8?, 0x14000288210?}, 0x1400062b700)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:613 +0x3e4
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x140002b8c80, {0x103911ae8?, 0x1400067fa10?}, 0x140006192c0)
        github.com/hashicorp/terraform-plugin-go@v0.14.2/tfprotov5/tf5server/server.go:748 +0x390
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x1038cf0c0?, 0x140002b8c80}, {0x103911ae8, 0x1400067fa10}, 0x14000210380, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.2/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x140002b41e0, {0x103915d00, 0x140003fe680}, 0x140006646c0, 0x140003fa0f0, 0x103e655b0, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1340 +0xaec
google.golang.org/grpc.(*Server).handleStream(0x140002b41e0, {0x103915d00, 0x140003fe680}, 0x140006646c0, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1713 +0x7c4
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.51.0/server.go:965 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 16
        google.golang.org/grpc@v1.51.0/server.go:963 +0x24c

Error: The terraform-provider-libvirt_v0.7.6 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by scream314** [comment]
I think this means you need the VM's UUID (`virsh dominfo --domain vlab-01 | grep UUID`) to import it.

**Comment by rorysavage77** [comment]
> @scream314 your are right. I just tested it. Import works with the UUID.
> 
> @rorysavage77 happy importing :)

Makes sense.  I appreciate the info.   Thanks!

**Comment by MrFinchMkV** [comment]
Just a short followup: `virsh domuuid vlab-01` returns the UUID directly :)
