### ISSUE TITLE
Crash on plan (read) after attaching additional disk externally

### ISSUE THREAD

**Issue by owaisaamir** [dmacvicar/terraform-provider-libvirt#592]
### Linux distribution

``` Centos7```

### Terraform version

```
Terraform v0.11.8
```

### Provider and libvirt versions

```
terraform-provider-libvirt 0.5.1
Compiled against library: libvirt 3.9.0
Using library: libvirt 3.9.0
Running hypervisor: QEMU 2.10.0
Running against daemon: 3.9.0
```
___

## Checklist

- [x] Is it a bug or something that does not work as expected? Please make sure you fill the version information below:

## Description of Issue/Question

Terraform crash observed while performing `terraform plan` (read) after attaching an existing LVM as additional disk to the domain.  Able to successfully attach an existing LVM using `virsh attach-disk` in `inline` option when creating the domain (`terraform apply`). A crash is however observed when performing `terraform plan`  after `terraform apply` (read after create).

Following panic is observed:

```
2019-04-11T16:18:07.522Z [DEBUG] plugin.terraform-provider-libvirt: panic: runtime error: invalid memory address or nil pointer dereference
2019-04-11T16:18:07.522Z [DEBUG] plugin.terraform-provider-libvirt: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xc47747]
2019-04-11T16:18:07.522Z [DEBUG] plugin.terraform-provider-libvirt: 
2019-04-11T16:18:07.522Z [DEBUG] plugin.terraform-provider-libvirt: goroutine 41 [running]:
2019-04-11T16:18:07.522Z [DEBUG] plugin.terraform-provider-libvirt: github.com/dmacvicar/terraform-provider-libvirt/libvirt.resourceLibvirtDomainRead(0xc42040acb0, 0xe193e0, 0xc4200730d0, 0x0, 0x0)
2019-04-11T16:18:07.522Z [DEBUG] plugin.terraform-provider-libvirt: 	/home/abuild/rpmbuild/BUILD/terraform-provider-libvirt-0.5.1/_build/src/github.com/dmacvicar/terraform-provider-libvirt/libvirt/resource_libvirt_domain.go:761 +0x1277
2019-04-11T16:18:07.522Z [DEBUG] plugin.terraform-provider-libvirt: github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc420368850, 0xc420075ea0, 0xe193e0, 0xc4200730d0, 0xc4203659b8, 0xc42036b601, 0x80000000000)
2019-04-11T16:18:07.522Z [DEBUG] plugin.terraform-provider-libvirt: 	/home/abuild/rpmbuild/BUILD/terraform-provider-libvirt-0.5.1/_build/src/github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:352 +0x17e
2019-04-11T16:18:07.522Z [DEBUG] plugin.terraform-provider-libvirt: github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc420368e70, 0xc420075e50, 0xc420075ea0, 0x7fa71404e6c8, 0x0, 0xc420368e70)
2019-04-11T16:18:07.522Z [DEBUG] plugin.terraform-provider-libvirt: 	/home/abuild/rpmbuild/BUILD/terraform-provider-libvirt-0.5.1/_build/src/github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:308 +0x9a
2019-04-11T16:18:07.522Z [DEBUG] plugin.terraform-provider-libvirt: github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc4202edaa0, 0xc42041e5d0, 0xc42041e710, 0x0, 0x0)
2019-04-11T16:18:07.522Z [DEBUG] plugin.terraform-provider-libvirt: 	/home/abuild/rpmbuild/BUILD/terraform-provider-libvirt-0.5.1/_build/src/github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:549 +0x4e
2019-04-11T16:18:07.522Z [DEBUG] plugin.terraform-provider-libvirt: reflect.Value.call(0xc420085f20, 0xc42000ebd8, 0x13, 0xffb233, 0x4, 0xc420037f20, 0x3, 0x3, 0x20002, 0xc420027f1c, ...)
2019-04-11T16:18:07.522Z [DEBUG] plugin.terraform-provider-libvirt: 	/usr/lib/golang/src/reflect/value.go:434 +0x905
2019-04-11T16:18:07.522Z [DEBUG] plugin.terraform-provider-libvirt: reflect.Value.Call(0xc420085f20, 0xc42000ebd8, 0x13, 0xc420027f20, 0x3, 0x3, 0xd7e1df, 0x1, 0x0)
2019-04-11T16:18:07.522Z [DEBUG] plugin.terraform-provider-libvirt: 	/usr/lib/golang/src/reflect/value.go:302 +0xa4
2019-04-11T16:18:07.522Z [DEBUG] plugin.terraform-provider-libvirt: net/rpc.(*service).call(0xc4200575c0, 0xc4203ba870, 0xc4203c84e0, 0xc420301100, 0xc4203ee1c0, 0xe1dee0, 0xc42041e5d0, 0x16, 0xe1df20, 0xc42041e710, ...)
2019-04-11T16:18:07.522Z [DEBUG] plugin.terraform-provider-libvirt: 	/usr/lib/golang/src/net/rpc/server.go:381 +0x142
2019-04-11T16:18:07.522Z [DEBUG] plugin.terraform-provider-libvirt: created by net/rpc.(*Server).ServeCodec
2019-04-11T16:18:07.522Z [DEBUG] plugin.terraform-provider-libvirt: 	/usr/lib/golang/src/net/rpc/server.go:475 +0x36b
2019/04/11 16:18:07 [ERROR] root.si2_s1: eval: *terraform.EvalRefresh, err: libvirt_domain.domain: unexpected EOF
2019/04/11 16:18:07 [ERROR] root.si2_s1: eval: *terraform.EvalSequence, err: libvirt_domain.domain: unexpected EOF
2019/04/11 16:18:07 [TRACE] [walkRefresh] Exiting eval tree: module.si2_s1.libvirt_domain.domain
2019/04/11 16:18:07 [TRACE] dag/walk: upstream errored, not walking "provider.libvirt.si2_s1 (close)"
2019/04/11 16:18:07 [TRACE] dag/walk: upstream errored, not walking "module.si2_s1.null_resource.wait_for_guest"
2019/04/11 16:18:07 [TRACE] dag/walk: upstream errored, not walking "module.si2_s1.data.null_data_source.values"
2019/04/11 16:18:07 [TRACE] dag/walk: upstream errored, not walking "module.si2_s1.module.puppet.var.provision_ip"
2019/04/11 16:18:07 [TRACE] dag/walk: upstream errored, not walking "module.si2_s1.module.puppet.null_resource.provision_puppet"
2019/04/11 16:18:07 [TRACE] dag/walk: upstream errored, not walking "provider.null (close)"
2019/04/11 16:18:07 [TRACE] dag/walk: upstream errored, not walking "root"
2019/04/11 16:18:07 [DEBUG] plugin: waiting for all plugin processes to complete...
2019-04-11T16:18:07.524Z [WARN ] plugin: error closing client during Kill: err="connection is shut down"
2019-04-11T16:18:07.524Z [DEBUG] plugin: plugin process exited: path=/opt/velocix/infra/terraform/terraform-provider-libvirt
```

### Setup

```
provider "libvirt" {
  uri   = "qemu+ssh://<user>@<Host_IP>/system?no_verify=1"
  alias = "test"
}

resource "libvirt_volume" "volume" {
  name     = "test_vol"
  pool     = "vg.a"
  format   = "raw"
  size     = "322122547200"

  provisioner "remote-exec" {
    inline = [
      "sudo /usr/bin/qemu-img convert -f qcow2 -O raw /tmp/centos7.qcow2 /dev/mapper/vg.a-test_vol"
    ]

    connection {
      timeout     = "30m"
      type        = "ssh"
      user        = "<user>"
      private_key = "<private_key>"
      host        = "<host_IP>"
    }
  }
}

resource "libvirt_domain" "domain" {
  name              = "test.domain"
  memory            = "16384‬"
  vcpu              = "4"

  disk {
    volume_id = "${libvirt_volume.volume.id}"
  }

  network_interface {
    network_name   = "default"
    hostname       = "test1"
    mac            = "AA:BB:CC:11:22:22"
    wait_for_lease = 1
  }
  
  cpu {
    mode = "host-passthrough"
  }

  graphics {
    type        = "vnc"
    listen_type = "address"
  }

  provisioner "remote-exec" {
    inline = [
		"sudo virsh attach-disk test.domain /dev/mapper/vg.b-existing vdb --live --config"
	]

    connection {
      timeout     = "30m"
      type        = "ssh"
      user        = "<user>"
      private_key = "<private_key>"
      host        = "<host_IP>"
    }
  }
}
```

### Steps to Reproduce Issue

`terraform apply`
`terraform plan`

Crash can also be observed by simply attaching an existing LVM using `virsh attach-disk` instead after the domain is created without `inline` and running `terraform plan`

___
## Additional information:

SELinux is enabled and is in Enforcing.

**Comment by MalloZup** [comment]
related to (https://github.com/dmacvicar/terraform-provider-libvirt/issues/569)

**Comment by MalloZup** [comment]
@owaisaamir  we merged this recently/and fixed it. I think this is fixed too. You might try the `master` branch and see if it works for you thx! Closing but feel free to comment/re-open
