### ISSUE TITLE
terraform-provider-libvirt_v0.6.14 plugin crashed with gitlab-ci terraform feature

### ISSUE THREAD

**Issue by jbhfenris** [dmacvicar/terraform-provider-libvirt#932]
##  System Information
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"

### Terraform version

Using terraform integration within Gitlab-ci (v14.1.8) and Gitlab runners

registry.gitlab.com/gitlab-org/terraform-images/stable:latest

### Provider and libvirt versions

0.6.14

___

## Description of Issue/Question

Crash at terraform plan stage when using gitlab-terraform feature with libvirt plugin :

gitlab-terraform plan
Initializing modules...
Initializing the backend...
Initializing provider plugins...
- Reusing previous version of dmacvicar/libvirt from the dependency lock file
- Reusing previous version of hashicorp/template from the dependency lock file
- Using previously-installed dmacvicar/libvirt v0.6.14
- Using previously-installed hashicorp/template v2.2.0
Terraform has been successfully initialized!
╷
│ Error: Request cancelled
│ 
│   with module.anthosnogpu.provider["registry.terraform.io/dmacvicar/libvirt"],
│   on modules/create_vm/providers.tf line 1, in provider "libvirt":
│    1: provider "libvirt" {
│ 
│ The plugin.(*GRPCProvider).ConfigureProvider request was cancelled.
╵
Stack trace from the terraform-provider-libvirt_v0.6.14 plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6812ea]
goroutine 98 [running]:
golang.org/x/crypto/ssh.publicKeyCallback.auth(0x11, {0xc000176020, 0x20, 0x20}, {0xc00004113b, 0x3}, {0xfaed10, 0xc00056c300}, {0xf9f480, 0xc000120600})
	golang.org/x/crypto@v0.0.0-20220112180741-5e0467b6c7ce/ssh/client_auth.go:2[35](https://gitlab.tech.orange/jeanbaptiste.hennequin/terraform-anthos-bm/-/jobs/28278383#L35) +0x24a
golang.org/x/crypto/ssh.(*connection).clientAuthenticate(0xc0001a2a80, 0xc000188540)
	golang.org/x/crypto@v0.0.0-20220112180741-5e0467b6c7ce/ssh/client_auth.go:63 +0x3a9
golang.org/x/crypto/ssh.(*connection).clientHandshake(0xc0001a2a80, {0xc0008101e0, 0x11}, 0xc000188540)
	golang.org/x/crypto@v0.0.0-20220112180741-5e0467b6c7ce/ssh/client.go:113 +0x26a
golang.org/x/crypto/ssh.NewClientConn({0xfc3a48, 0xc00000e178}, {0xc0008101e0, 0x11}, 0xc00010f800)
	golang.org/x/crypto@v0.0.0-20220112180741-5e0467b6c7ce/ssh/client.go:83 +0x12b
golang.org/x/crypto/ssh.Dial({0xe2[38](https://gitlab.tech.orange/jeanbaptiste.hennequin/terraform-anthos-bm/-/jobs/28278383#L38)f1, 0x5}, {0xc0008101e0, 0x11}, 0xc00010f800)
	golang.org/x/crypto@v0.0.0-20220112180741-5e0467b6c7ce/ssh/client.go:190 +0x59
github.com/dmacvicar/terraform-provider-libvirt/libvirt/uri.(*ConnectionURI).dialSSH(0xc00010f9c8)
	github.com/dmacvicar/terraform-provider-libvirt/libvirt/uri/ssh.go:130 +0x465
github.com/dmacvicar/terraform-provider-libvirt/libvirt/uri.(*ConnectionURI).DialTransport(0xc000041130)
	github.com/dmacvicar/terraform-provider-libvirt/libvirt/uri/connection_uri.go:83 +0x45
github.com/dmacvicar/terraform-provider-libvirt/libvirt.(*Config).Client(0xe4d2b3)
	github.com/dmacvicar/terraform-provider-libvirt/libvirt/config.go:35 +0x73
github.com/dmacvicar/terraform-provider-libvirt/libvirt.providerConfigure(0xc000484850)
	github.com/dmacvicar/terraform-provider-libvirt/libvirt/provider.go:68 +0xff
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Configure(0xc0001a2180, 0xc00000e110)
	github.com/hashicorp/terraform-plugin-sdk@v1.9.0/helper/schema/provider.go:275 +0xb4
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).Configure(0xc00000e088, {0xc000608580, 0x516766}, 0xc000608580)
	github.com/hashicorp/terraform-plugin-sdk@v1.9.0/internal/helper/plugin/grpc_provider.go:487 +0x1d2
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_Configure_Handler({0xdf51[40](https://gitlab.tech.orange/jeanbaptiste.hennequin/terraform-anthos-bm/-/jobs/28278383#L40), 0xc00000e088}, {0xfb64b0, 0xc000883320}, 0xc0000dccc0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk@v1.9.0/internal/tfplugin5/tfplugin5.pb.go:3251 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001b2[48](https://gitlab.tech.orange/jeanbaptiste.hennequin/terraform-anthos-bm/-/jobs/28278383#L48)0, {0xfc3c00, 0xc00056c000}, 0xc0006ec200, 0xc000883200, 0x1[55](https://gitlab.tech.orange/jeanbaptiste.hennequin/terraform-anthos-bm/-/jobs/28278383#L55)bf38, 0x0)
	google.golang.org/grpc@v1.27.1/server.go:1024 +0xd1e
google.golang.org/grpc.(*Server).handleStream(0xc0001b2480, {0xfc3c00, 0xc000[56](https://gitlab.tech.orange/jeanbaptiste.hennequin/terraform-anthos-bm/-/jobs/28278383#L56)c000}, 0xc0006ec200, 0x0)
	google.golang.org/grpc@v1.27.1/server.go:1313 +0xa56
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.27.1/server.go:[72](https://gitlab.tech.orange/jeanbaptiste.hennequin/terraform-anthos-bm/-/jobs/28278383#L72)2 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.27.1/server.go:720 +0xef
Error: The terraform-provider-libvirt_v0.6.14 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Setup

provider.tf file

provider "libvirt" {
  #uri = "qemu:///system"
  uri   = "qemu+ssh://IP ADDRESS/system?keyfile=/root/.ssh/ssh_priv&sshauth=privkey"
}

Private ssh key have been provisioned with a before_script entry just before calling the "plan" command

**Comment by jbhfenris** [comment]
Not an issue. 
Problem of copy ssh private key at the correct format on the gitlab-ci runner.
